version: '3.8'

services:
  neode-web:
    image: node:18-alpine
    working_dir: /app
    expose:
      - "80"
    ports:
      - "8100:80"
    command: 
      - sh
      - -c
      - |
        set -e
        apk add --no-cache git nginx net-tools
        
        # Clone repo if not exists, otherwise pull updates
        if [ ! -d ".git" ]; then
          git clone https://github.com/Zazawowow/Neode.git .
        else
          git pull origin master || true
        fi
        
        cd web
        
        # Clean install with all dependencies including devDependencies
        echo "Installing all dependencies..."
        rm -rf node_modules
        
        # Use npm install to get all dependencies including devDependencies
        echo "Running npm install with legacy peer deps and dev dependencies..."
        npm install --legacy-peer-deps --include=dev
        
        # Verify we have all packages (should be 1400+, not 216)
        echo "Installed packages count: $(npm list --depth=0 2>/dev/null | wc -l)"
        
        # Verify Angular CLI is available
        echo "Checking for Angular CLI..."
        if ! npx ng version >/dev/null 2>&1; then
          echo "Angular CLI not working, installing globally..."
          npm install -g @angular/cli@14 --legacy-peer-deps
        fi
        
        # Handle patch-db dependency
        if [ -d "../patch-db/client" ]; then
          echo "Building patch-db dependencies..."
          npm run build:deps || echo "Warning: build:deps failed, continuing..."
        else
          echo "Warning: patch-db/client not found, creating mock dependency..."
          
          # Remove any existing symlink created by npm install
          echo "Removing existing patch-db-client symlink..."
          rm -rf node_modules/patch-db-client 2>/dev/null || true
          
          # Create mock patch-db-client directory and files
          echo "Creating mock patch-db-client module..."
          mkdir -p node_modules/patch-db-client
          echo '{"name": "patch-db-client", "version": "1.0.0", "main": "index.js", "types": "index.d.ts"}' > node_modules/patch-db-client/package.json
          echo 'class PatchDB { watch$() { return { pipe: () => ({ subscribe: () => ({}) }) }; } start() {} stop() {} get cache$() { return { pipe: () => ({ subscribe: () => ({}) }) }; } } class Update {} class Bootstrapper {} class DBCache {} class Dump {} class Revision {} class Operation {} class PatchOp {} class RemoveOperation {} function pathFromArray() { return ""; } module.exports = { PatchDB, Update, Bootstrapper, DBCache, Dump, Revision, Operation, PatchOp, RemoveOperation, pathFromArray };' > node_modules/patch-db-client/index.js
          echo 'export class PatchDB<T = any> { watch$(path1?: string, path2?: string, path3?: string): any; start(bootstrapper: any): void; stop(): void; get cache$(): any; } export class Update<T = any> {} export class Bootstrapper<T = any> {} export class DBCache<T = any> {} export class Dump<T = any> {} export class Revision {} export class Operation {} export class PatchOp {} export class RemoveOperation {} export function pathFromArray(arr: any[]): string;' > node_modules/patch-db-client/index.d.ts
          
          echo "Mock patch-db-client setup complete"
          # Debug: check what was created
          echo "Created files in node_modules/patch-db-client:"
          ls -la node_modules/patch-db-client/ 2>/dev/null || echo "Directory not found"
        fi
        
        # Build the UI
        echo "Building UI application..."
        npm run build:ui
        
        # Setup nginx
        mkdir -p /usr/share/nginx/html
        cp -r dist/raw/ui/* /usr/share/nginx/html/
        cp -r projects/shared/assets /usr/share/nginx/html/
        
        # Configure nginx
        rm -f /etc/nginx/conf.d/default.conf
        echo 'server { listen 80 default_server; server_name _; root /usr/share/nginx/html; index index.html; location / { try_files $uri $uri/ /index.html; } location /assets { alias /usr/share/nginx/html/assets; expires 1y; } location /health { access_log off; return 200 "healthy"; add_header Content-Type text/plain; } }' > /etc/nginx/conf.d/neode.conf
        echo 'events { worker_connections 1024; } http { include /etc/nginx/mime.types; include /etc/nginx/conf.d/*.conf; default_type application/octet-stream; }' > /etc/nginx/nginx.conf
        
        # Test and start nginx
        nginx -t
        echo "Starting nginx on port 80..."
        
        # Ensure nginx is listening on all interfaces
        echo "Checking nginx configuration..."
        cat /etc/nginx/conf.d/neode.conf
        
        # Start nginx in foreground
        echo "Starting nginx on 0.0.0.0:80..."
        exec nginx -g 'daemon off;'
    container_name: neode-web
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.neode.rule=Host(`neode.local`)"
      - "traefik.http.routers.neode.entrypoints=web"
      - "traefik.http.services.neode.loadbalancer.server.port=80"
    networks:
      - neode-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  neode-network:
    driver: bridge