version: '3.8'

services:
  # Neode Demo - Frontend Only (No Backend Required)
  neode-demo:
    build:
      context: https://github.com/Zazawowow/Neode.git
      dockerfile: Dockerfile.demo
    container_name: neode-demo
    ports:
      - "8100:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DEMO_MODE=true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.neode.rule=Host(`neode.local`)"
      - "traefik.http.routers.neode.entrypoints=web"
      - "traefik.http.services.neode.loadbalancer.server.port=80"
    networks:
      - neode-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  neode-network:
    driver: bridge

