// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PublicDomainConfig } from "./PublicDomainConfig"

export type Domains = {
  public: { [key: string]: PublicDomainConfig }
  private: Array<string>
}
