// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackageVersionInfo } from "./PackageVersionInfo"
import type { Version } from "./Version"

export type GetPackageResponseFull = {
  categories: string[]
  best: { [key in Version]?: PackageVersionInfo }
  otherVersions: { [key in Version]?: PackageVersionInfo }
}
