// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Category } from "./Category"
import type { PackageId } from "./PackageId"
import type { PackageInfo } from "./PackageInfo"

export type PackageIndex = {
  categories: { [key in string]?: Category }
  packages: { [key in PackageId]?: PackageInfo }
}
